### ISSUE TITLE
Tweets don't load after authentication on http://brunch.io/twitter/public/

### ISSUE THREAD

**Issue by bdefore** [brunch/twitter#3]
On http://brunch.io/twitter/public/ following authentication I'm not seeing any list of tweets. Just my profile information on the left, for all browsers.

On my local build and hosting of the codebase, following authentication the list comes up fine, however none of the nav bar items function.

Reminds me of issues I'll see when I've configured Facebook to use the wrong host URL between localhost/mydomain.com.

**Comment by ocdavid** [comment]
I see the same problem -- both on  http://brunch.io/twitter/public/,  and also when I run the site locally.

Login appears to work (my Twitter account info is shown correctly), but no tweets, no @mentions, no functioning logout.

**Comment by paulmillr** [comment]
confirmed.

seems like twitter changed their api again. or their `@anywhere`.js. fuck

**Comment by paulmillr** [comment]
fixed

**Comment by milushov** [comment]
still not work for me

```
Uncaught TypeError: Object #<Object> has no method 'anywhere'  app.js:583
```

**Comment by paulmillr** [comment]
works alright for me. even multiple login - logout actions
